### ISSUE TITLE
Ability to ignore certain images

### ISSUE THREAD

**Issue by torrobinson** [imulus/retinajs#135]
Is there the ability to ignore an image? If I'm already dealing with a higher resolution image being shrunk, which doesn't need an @2x version, the script will throw errors to the browser of "_____@2x.png" not found. Is there a way to have retina.js ignore specific images? Say with a special class? Or is it a standard to optimize all images for both retina and non-retina displays?

![image](https://f.cloud.github.com/assets/4401999/2368930/1cca56d0-a7c4-11e3-821d-cc54ad0809d1.png)

**Comment by mosaiceye** [comment]
What if you have like 50 that you want to exclude, then what? I have 50 that don't need retina. Can I add an attribute like retinajs-ignore="true" to an image tag, is there an option for that? <img src="../" retinajs-ignore="true" />

**Comment by joshuaiz** [comment]
Add data-no-retina and the script will ignore them.
