### ISSUE TITLE
is_external() check prevents support for S3 CORS

### ISSUE THREAD

**Issue by wkoffel** [imulus/retinajs#149]
Given the increasingly common support for CORS to allow cross-origin XHR requests, it'd be nice to have a way to explicitly allow certain external domains that we know have been configured correctly.

For example, a CORS configuration like the following (too permissive, obviously should be locked down tighter to specific domains) will allow retina.js to do what it needs to with a HEAD request.
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

However, in current versions, the request is never made because `is_external()` is checked, returns true, and the call to `check_2x_variant()` always returns false, so no retina variant swap is made.

In my case, I fixed this with a one line change:

```
111:        if (this.is_external() && !this.path.match(/s3.amazonaws.com/i)) {
```

But it might make sense to have an attribute like _data-allow-external_, or _data-allowed-domains_, which provides a list of domains we know have proper CORS support, and therefore can be treated like the origin domain by retina.js

**Comment by nickdnk** [comment]
I have been struggling with this for an entire day. As of now, do I need to change anything in retina.js if my images are not hosted on the same domain? I don't see my browser making any requests (HEAD, OPTIONS etc) to S3/CloudFront at all. I have enabled CORS on my S3 bucket and whitelisted Origin header + allowed OPTIONS method. What do I need to do to get this to work?
