### ISSUE TITLE
bower install - wrong version

### ISSUE THREAD

**Issue by larzKke** [imulus/retinajs#176]
After ```bower install retainajs``` the bower.json file has Version **1.2.0** and the "main" Path: **"main": "build/js/retina-1.2.0.js"** is wrong.

**Comment by shea256** [comment]
@Grawl thanks, this worked beautifully

**Comment by Grawl** [comment]
@shea256 to you and others I suggest to try dense.js as an alternative with clearer naming of things.

**Comment by shea256** [comment]
Interesting. Only unfortunate thing is it looks like I'd have to use jquery for it.

**Comment by shea256** [comment]
And what do you mean by "clearer naming of things"?

**Comment by Grawl** [comment]
I mean that you have to write “HDPI” or “XHDPI” or “LDPI” instead of “Retina” or “not Retina”.
