### ISSUE TITLE
Replacing a paths into background-image in inline styles?

### ISSUE THREAD

**Issue by Grawl** [imulus/retinajs#178]
If I has this:

```html
<img src=…>
```

It is very similar to this:

```html
<div style='background-image: url(…)'></div>
```

So let's replace this image paths too!

**Comment by jdahdah** [comment]
+1 I'm using retina.js in production and didn't realize this was not supported (yes, my bad). Does anyone have a quick fix for this, or can you recommend a script that does not conflict with retina.js? That would be tremendously helpful.

**Comment by Grawl** [comment]
@jdahdah I just found https://github.com/gocom/dense but didn't use it yet

**Comment by jdahdah** [comment]
@Grawl Thanks, but apparently you submitted https://github.com/gocom/dense/issues/5 yourself two weeks earlier as that script doesn't support it either, no?

**Comment by Grawl** [comment]
@jdahdah oh I just realized that Dense has last commit in a year ago…

**Comment by isaaki** [comment]
+1

This is huge.

**Comment by Lori1072** [comment]
Thanks guys, WHat is the issue>

**Comment by vlrprbttst** [comment]
+1
