### ISSUE TITLE
Is it possible to make the @2x detection smarter to only make 1 request? Instead of requesting regular and retina?

### ISSUE THREAD

**Issue by dezmathio** [imulus/retinajs#181]
As title says: Is it possible to make the @2x detection smarter to only make 1 request? Instead of requesting regular and retina?

I sort of customized retina.js with a snippet to only request an @2x if the image has a specific selector, like data-retina, instead of checking for all img tags.

Unfortunately it's still loading the normal images too, in terms of looks, it looks fine because it loads the regular one, and then replaces it with the @2x one making it look like the image got smoother as the page loaded.

However, that extra bandwidth is a problem if we want to optimize things for our users loading our page.
Are there any approaches you guys can think of to work around this/make this more efficient? 

The only thing that occurred to me was running retina.js on $document.ready before all the requests are made to all of the images. But I don't think retinajs overrides the original image request... it just makes that retina request after the fact.

Any ideas?

**Comment by ridom** [comment]
I know that it's an old issue but I also have detected that behaviour (watching network tab in devtools).

What do you think about simply enable retina.js using the same way that the script itself detects devices?

So if the user is not loading from an apple device (or device-pixel-ratio is not reach), the script is not enabled while if an apple device is detected, the script is loaded.

What do you think about that?
Could it be a solution?

**Comment by benmarten** [comment]
That might work... I think in general using the html5 tag `srcset`is the way to go now anyways ;)
