### ISSUE TITLE
Retina images dissapears when initially in hidden blocks (w. FIX)

### ISSUE THREAD

**Issue by nukinuki** [imulus/retinajs#189]
If image is in hidden block — it gets "width: 0, height: 0" after replacement. Even if there was width and height specified inline.

Here's a quick fix in retina.js 1.3.0 on line 167:
    if (config.force_original_dimensions && that.el.offsetHeight > 0)

(additional condition added to prevent retina.js from setting zero dimensions)

**Comment by dereknutile** [comment]
I believe this was supposed to be resolved in #106.

**Comment by jungbunzlav** [comment]
Its still not resolved in 1.3.0

**Comment by JMarqz** [comment]
Still not fixed in 1.3.0 version, but the @sakong solution works for me. Thanks a lot!
Maybe this would be added to the master files.

**Comment by anhnt** [comment]
:+1: thanks @sakong it works

**Comment by youcefhaouatis** [comment]
Thanks @sakong it works as I expected.
