### ISSUE TITLE
retina.js creates 404 error Denial of Service effect on high traffic sites

### ISSUE THREAD

**Issue by davidfavor** [imulus/retinajs#232]
In WordPress, the entire LAMP stack must run to generate the 404 page content.

This any page using multiple images with no retina equivalent take site down.

Problem shows up easily on pages with many images + no retina equivalent.

As traffic increases, 404s increase till site comes down.

Please fix this problem, as it's been occurring for at least 2 years.

Thanks.

**Comment by davidfavor** [comment]
http://stackoverflow.com/questions/13704317/supressing-404s-in-retina-js-library gives a great overview of one fix approach, which seems somewhat acceptable.

This fix caches 404s + just skips serving image.

Problem with this approach is cache could become very large + will require a way to clear a cache entry or entire cache, to pickup new retina images when they're generated.

**Comment by davidfavor** [comment]
For sites with no retina images, where a WordPress theme includes retina.js, the fix is...

1) cd directory where retina.js lives

2) rm retina.js

3) touch retina.js

4) chmod www-data:www-data retina.js

Where www-data (Ubuntu Apache user/group) is the user/group for your site.

**Comment by strues** [comment]
This should be resolved in the latest release. Sorry for the wait.
