### ISSUE TITLE
Reload / Reinit retinajs programmatically

### ISSUE THREAD

**Issue by ticlekiwi** [imulus/retinajs#240]
Hi!
Great job with retinajs! it is an essential for every project!

I have a little question : is it possible and how reinit retinajs programmatically ? 

Sometimes I dynamically load part of a page and I would relaunch retinajs to my new content...

Thanks by advance!

**Comment by jgnewman** [comment]
@ticlekiwi Great suggestion! We're working on releasing version 2.0 _very_ soon and this feature will be built in.

**Comment by ticlekiwi** [comment]
@jgnewman : Wonderfull ! Thanks! 
I close this issue.
