### ISSUE TITLE
skip svg

### ISSUE THREAD

**Issue by benatkin** [imulus/retinajs#30]
I got an email from someone who's using svg in img tags, saying that retina.js tried to swap those. I verified it and pushed up a small fix to my repo. I haven't added tests so I haven't sent a pull request yet.

**Comment by aleblanc** [comment]
Hello,

A quick solution is to replace the suffixReplace method (if you don't want to add the data-no-retina tag) :

>     function suffixReplace (match) {
    	if(match==".svg"){
    		return match;
    	}else{
    		return config.retinaImageSuffix + match;
    	}
    }
