### ISSUE TITLE
Doesn't work for dynamically inserted images?

### ISSUE THREAD

**Issue by orbitaloop** [imulus/retinajs#41]
I tried to use retina.js inside a one page js app, the DOM is dynamically generated with JS template. 
But it looks like it's not working.
Does retina.js works only on static pages?
Thanks in advance,

Best regards,
Sam

**Comment by elsurudo** [comment]
If https://github.com/imulus/retinajs/pull/197 gets merged in, you'll be able to call `Retina.process()` to reprocess.

**Comment by thesergeev** [comment]
Try this:
<img src="" onload="if ( $.isFunction($.fn.retina) ) { $(this).retina(); }" />
