### ISSUE TITLE
Not working in Rails 3.2.8 Production

### ISSUE THREAD

**Issue by Lordnibbler** [imulus/retinajs#59]
Once Rails 3.2.8 asset pipeline precompiles/minifies Retina.js 0.0.2 and combines it with my other JS files into application.js, Retina.js no longer fires.  It works perfectly in development.

**Comment by citysheep** [comment]
the data-at2x is correctly added in my Rails app in production/staging with the url of the @2x version of the image. However, looks like retinajs failed to switch the source when it is on Retina display. It works fine in development mode.
