### ISSUE TITLE
LESS question and problem

### ISSUE THREAD

**Issue by cclloyd** [imulus/retinajs#82]
Question:  Is it possible to have the less css and my normal css in the same file?  It seems to not work unless I have a less.css and a styles.css.

Problem:  The mixin is prepending my url to the image path.  Like, if I put in "_img/background.jpg" for the path, it outputs it as "(http://mydomain.com'_img/background.jpg')"

**Comment by jgnewman** [comment]
Sorry for the late response, there's something like this going on in one of the other issues as well.

LESS is designed to run JavaScript within your functions to allow some more complex calculations. The line in the mixin that generates the 2x path looks like this:

```less
@at2x_path: ~`@{path}.replace(/\.\w+$/, function(match) { return "@2x" + match; })`
```

You can run that line manually and drop in your path if you'd like. That would look like this:

```javascript
'_img/background.jpg'.replace(/\.\w+$/, function(match) { return "@2x" + match; });
```

And the return looks like this:

```javascript
'_img/background@2x.jpg'
```

Note that when you run that line manually, you'll get the correct output. The LESS mixin does not alter that string anywhere else so I'm afraid I can't say exactly what's causing the error in your code. I imagine it could be a bug within LESS.

Let me know if this helps or if you think I misunderstood. If it's a problem with LESS, I'll close this and either you or I can file an issue with LESS.

**Comment by neoziro** [comment]
@jgnewman very very late response you mean! Thank you.
