### ISSUE TITLE
Images with display:none get 0x0 dimensions

### ISSUE THREAD

**Issue by jxmallett** [imulus/retinajs#97]
Whilst trying to get an image slider working with retina images I discovered that if images have the CSS property 'display:none' they will be assigned '0' to their width and height attributes, even if width and height are specified in the CSS or HTML.

I fixed this by checking that offsetWidth and offsetHeight are non-zero before assignment:

if (that.el.offsetWidth && that.el.offsetHeight) {
  that.el.setAttribute('width', that.el.offsetWidth);
  that.el.setAttribute('height', that.el.offsetHeight);
}

**Comment by jungbunzlav** [comment]
Yeah, still broken... Please fix!

**Comment by JMarqz** [comment]
This bug still not fixed in the 1.3.0 version.

**Comment by pioz** [comment]
Same problem with v1.3.0

**Comment by jamesxliu** [comment]
Boy, they sure took their sweet time to roll in my proposed changes into the repo. Still, sweet, sweet validation at last! :lollipop:

**Comment by christoshrousis** [comment]
Had this issue today, Can confirm resolved in above fork.... +1

**Comment by mikegyi** [comment]
+1

**Comment by zhe** [comment]
Still this issue today, v1.3.0

**Comment by pioz** [comment]
+1

**Comment by cgpro** [comment]
+1

**Comment by cgpro** [comment]
http://dense.rah.pw/
Works fine, also with hidden elements. (you only have to edit the glue var from _ to @)

**Comment by Kamokamocsai** [comment]
KamoKamoAgiZsombor

**Comment by kaghee** [comment]
masodikharmadikelsoelso

**Comment by kaghee** [comment]
elsoharmadik
